CB/urls.py
from django.urls import path, include
from django.contrib import admin
from . import views

app_name = "CB"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', views.homepage, name='Homepage'),
    path('authorization', views.auth, name='Authorization'),
    path('profile', views.profile, name='Profile'),
    path('college_page', views.college_page, name='CollegePage'),
    path('add_connection', views.add_connection, name='AddConnection'),
    path('ask_question', views.ask_question, name= 'AskQuestion'),
    path('answer_question', views.answer_question, name= 'AnswerQuestion'),
    path('write_review', views.write_review, name='WriteReview'),
    path('follow_college', views.follow_college, name='FollowCollege'),
]

djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('CB.urls')),
]

CB/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class College(models.Model):
    OWNED_TYPES = (
        ('C', 'Central University'),
        ('D', 'Deemed University'),
        ('P', 'Private University'),
    )
    college_name = models.CharField(max_length=10000, unique=True)
    location = models.CharField(max_length=500)
    year = models.PositiveIntegerField(default='')
    specialization = models.CharField(max_length=500)
    owned = models.CharField(choices=OWNED_TYPES, max_length=50, default='')

    def __str__(self):
        return self.college_name


class UserDetails(models.Model):
    USER_TYPE_CHOICES = (
        ('CS', 'College Student'),
        ('F', 'Faculty'),
        ('CAS', 'College Aspirant'),
        ('O', 'Others'),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    college = models.ForeignKey(College, to_field='college_name', on_delete=models.CASCADE, default='', blank=True)
    user_type = models.CharField(max_length=50, choices=USER_TYPE_CHOICES)


class CollegeReview(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    college = models.ForeignKey(College, to_field='college_name', on_delete=models.CASCADE)
    review = models.CharField(default='', max_length=500)
    time = models.DateTimeField(default='')


class CollegeQuestion(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    college = models.ForeignKey(College, to_field='college_name', on_delete=models.CASCADE)
    question = models.CharField(default='', max_length=500, unique=True)
    time = models.DateTimeField(default='')

    def __str__(self):
        return self.question


class QuestionAnswers(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(CollegeQuestion, to_field='question', on_delete=models.CASCADE)
    college = models.ForeignKey(College, to_field='college_name', on_delete=models.CASCADE)
    answer = models.CharField(default='', max_length=1000, blank=True)
    time = models.DateTimeField(default='')

    def __str__(self):
        return self.answer


class FollowCollege(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    college = models.ForeignKey(College, to_field='college_name', on_delete=models.CASCADE)

    def __str__(self):
        return self.college_id

CB/views.py
from django.shortcuts import render, HttpResponse, redirect
from .models import College, CollegeReview, CollegeQuestion, FollowCollege, UserDetails, QuestionAnswers
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from datetime import date, datetime


def homepage(request):
    data = College.objects.values('college_name')
    li = []
    for i in range(len(data)):
        li.append(data[i]['college_name'])
    if request.user.is_authenticated is True:
        log = 0
    else:
        log = 1
    return render(request, 'homepage.html', {'list': li, 'log': log})


def auth(request):
    if request.method == 'POST':
        name = request.POST['name']
        password = request.POST['password']

        user = authenticate(request, username=name, password=password)
        if user is None:
            email = request.POST['email']
            User.objects.create_user(username=name, email=email, password=password)
            user = authenticate(request, username=name, password=password)
            login(request, user)

            return redirect("CB:Profile")

        else:
            login(request, user)
            return redirect("CB:Profile")

    return render(request, 'auth.html')


def profile(request):
    username = request.user.username
    id = request.user.id
    name = username[0].capitalize() + username[1:]
    try:
        coll_foll = FollowCollege.objects.filter(user=id)

    except FollowCollege.DoesNotExist:
        coll_foll = ''
    try:
        review = CollegeReview.objects.filter(user=id)
    except CollegeReview.DoesNotExist:
        review = ''
    try:
        question = CollegeQuestion.objects.filter(user=id)
    except CollegeQuestion.DoesNotExist:
        question = ''
    if request.user.is_authenticated is True:
        log = 0
    else:
        log = 1
    return render(request, 'profile.html',
                  {'username': name, 'log': log, 'collegefollowing': coll_foll, 'review': review,
                   "question": question})


def user_type(request):
    if request.method == 'POST':
        user = request.user
        usertype = request.POST['usertype']
        UserDetails.objects.create(user=user, user_type=usertype)
    return redirect('CB:Profile')


@login_required()
def college_page(request):
    global college, log, review, followers
    college = College.objects.get(college_name=request.GET['college'])

    try:
        review = CollegeReview.objects.filter(college=college)
    except CollegeReview.DoesNotExist:
        review = ''
    try:
        question = CollegeQuestion.objects.filter(college=college)
    except CollegeQuestion.DoesNotExist:
        question = ''
    try:
        answer = QuestionAnswers.objects.filter(college=college)
    except QuestionAnswers.DoesNotExist:
        answer = ''
    try:
        followers = FollowCollege.objects.filter(college__college_name=college)
    except FollowCollege.DoesNotExist:
        followers = ''
    if request.user.is_authenticated is True:
        log = 0
    else:
        log = 1
    return render(request, 'college_page.html', {'college': college, 'log': log, 'review': review,
                                                 "question": question, 'answer': answer, 'followers': followers.count()})


def add_connection(request):
    return 1


def ask_question(request):
    if request.method == 'POST':
        question = request.POST['question']
        college = College.objects.get(college_name=request.POST['college'])
        user = request.user
        CollegeQuestion.objects.create(college=college, user=user, question=question, time=datetime.now())
        return redirect('/college_page?college=%s' % college)


def answer_question(request):
    if request.method == 'POST':
        answer = request.POST['answer']
        college = College.objects.get(college_name=request.POST['college'])
        question = CollegeQuestion.objects.get(question=request.POST['question'])
        user = request.user
        QuestionAnswers.objects.create(user=user, question=question, college=college, answer=answer,
                                       time=datetime.now())
        return redirect('/college_page?college=%s' % college)


def write_review(request):
    if request.method == 'POST':
        review = request.POST['review']
        college = College.objects.get(college_name=request.POST['college'])
        user = request.user
        CollegeReview.objects.create(college=college, user=user, review=review, time=datetime.now())
        return redirect('/college_page?college=%s' % college)
    return 1


def follow_college(request):
    if request.method == 'POST':
        user = request.user
        coll = request.POST['college']
        college = College.objects.get(college_name=coll)
        FollowCollege.objects.create(user=user, college=college)
    return redirect('/college_page?college=%s' % college)

templates/auth.html
<html lang="en">
<head>
    <style>
        body{
            margin-top: 15vh;
            font-size: 2vh;
            color: white;
        }
        ul{
            text-align:center;

        }
        ul.login_signup_title li{
            display: inline;
            margin: 7vh;
        }

        li.form{
            display: block;
        }
        .forms{
            margin-top: 10vh;
        }
        input{
            width: 20vh;
            height: 3vh;
            border: none;
            background-color: #094067;
            border-bottom: 1px solid black;
        }

    </style>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<div class="container" style="background-color: #094067; margin-left:40rem; margin-right:40rem; padding: 2rem; border-radius: 1rem; height: 30rem">
<div class="login_signup">
    <ul class="login_signup_title">
        <li class="signup_title" onclick="signup();" style="border-bottom: white solid 3px" id="signup_title">Signup</li>
        <li class="signin_slider" onclick="signin();" style="border-bottom: none" id="signin_title">Signin</li>
    </ul>
</div>
<div class="forms">
<form method="post" class="signup" id="signup" style="display:block;">
    {% csrf_token %}
    <ul>
        <li class="form">
            <p>Name</p>
            <input name="name" class="name">
        </li>
        <li class="form">
            <p>Email</p>
            <input name="email" class="email">
        </li>
        <li class="form">
            <p>Password</p>
            <input type="password" name="password" class="password" id="id_password">
            <p onclick="show_pass()" style="font-size: 1.2vh">showpassword</p>
        </li>


    <button type="submit">Signup</button>
        </ul>
</form>

<form method="post" class="signin" id="signin" style="display:none;">
    {% csrf_token %}
    <ul>
        <li class="form">
            <p>Name</p>
            <input name="name" class="name">
        </li>
        <li class="form">
            <p>PassWord</p>
            <input type="password" name="password" class="password" id="id_password1">
            <p onclick="show_pass1()" style="font-size: 1.2vh">showpassword</p>
        </li>
    <button type="submit">login</button>
        </ul>
</form>
</div>
</div>

</body>
</html>

<script>
    function signin(){
        var signin = document.getElementById("signin");
        var signup = document.getElementById("signup");
        var signup_title = document.getElementById("signup_title");
        var signin_title = document.getElementById("signin_title");
            signin.style.display = "block";
            signup.style.display = "none";
            signin_title.style.borderBottom = "white solid 3px";
            signup_title.style.borderBottom = "none";
    }
    function signup(){
        var signin = document.getElementById("signin");
        var signup = document.getElementById("signup");
        var signup_title = document.getElementById("signup_title");
        var signin_title = document.getElementById("signin_title");
            signin.style.display = "none";
            signup.style.display = "block";
            signin_title.style.borderBottom = "none";
            signup_title.style.borderBottom = "white solid 3px";
    }
    function show_pass() {
        var pass = document.getElementById("id_password");
        if (pass.type === "password") {
            pass.type = "text";
        } else {
            pass.type = "password";
        }
    }
    function show_pass1() {
        var pass = document.getElementById("id_password1");
        if (pass.type === "password") {
            pass.type = "text";
        } else {
            pass.type = "password";
        }
    }
</script>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src=" https://unpkg.com/@popperjs/core@2"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">


    <style>
        .navbar{
            background-color: #094067;
             box-shadow: 0 0 3px black;
        }
        .navbar a{
            color: #fffffe;
        }
        ul{
            margin-right: 6vh;
        }
        .navbar-nav li{
            margin-right: 2vh;
        }
        .navbar-brand{
            margin-left: 8vh;
        }

    </style>
    {% block head %}
    {% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg">
  <a class="navbar-brand" href="#">College Book</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'CB:Homepage' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'CB:Profile' %}">Profile</a>
      </li>
        {% if  log  is 0 %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'CB:logout' %}?next=/">Logout<span class="sr-only">(current)</span></a>
      </li>
        {% else %}
        <li class="nav-item">
        <a class="nav-link" href="{% url 'CB:Authorization' %}">Login<span class="sr-only">(current)</span></a>
      </li>
        {% endif %}
    </ul>
  </div>
</nav>
{% block body %}
{% endblock %}
<div class="card-footer" style="background-color: #094067; text-align: center; color: #fffffe; margin-top: 65vh">
    <p > CollegeBook</p>
</div>
</body>
</html>

templates/college_page.html
{% extends 'base.html' %}
{% block head %}
    <style>
        .head{
            margin-top: 4rem;
        }
        body{
            background-color: #F2F2F2;
        }


    </style>
{% endblock %}

{% block body %}
    <div class="container" style="background-color: white;padding-top: 5vh">
        <div class="container head">
            <div class="nav">
                <h1 class="nav-item">{{ college }}</h1>
                <p class="text-muted nav-item" style="margin-top: 1rem; margin-left: 2rem"> {{ college.location }}</p>
            </div>
            <p>{{ college.year }}</p    >
            <p>Specialization- {{ college.specialization }}</p>
             <form  method="post" action="{% url 'CB:FollowCollege' %}">
                {% csrf_token %}
                <input type="hidden" name="college" value='{{ college }}'>
                <button class="btn btn-primary align-middle" type="submit" value="Follow">Follow</button>
            </form>
        </div>
        <div class="container">
            Followers :{{ followers }}
        </div>
    <div class="container" style="margin-top: 10vh">
        <h3 class="text-muted">Activity</h3>
        <div class="container-fluid">
            <h4>Questions</h4>
            {% for i in question %}
                <div class="container-fluid", style="background-color: #F2F2F2; border-radius: 1rem; margin-top: 2rem">
                <h5>Q. {{ i.question }}  ~{{ i.user }}</h5>
                {% for j in answer %}
                    {% if j.question == i%}
                        <p style="background-color: #fffffe">{{ j.answer }}  ~{{ j.user }}</p>
                    {% endif %}
                {% endfor %}

            <div class="ask question">
            <form method="post"  action="{% url 'CB:AnswerQuestion'%}">
                 {% csrf_token %}
                <label>
                    <input class="form-control" placeholder="answer question" name="answer">
                     <input type="hidden" name="college" value='{{ college }}'>
                    <input type="hidden" name="question" value='{{ i }}'>
                </label>
                <button class="btn-outline-primary" style="border-radius: 1vh; width: 10%" type="submit">Submit</button>
            </form>
        </div>
         </div>
        {% endfor %}
         <div class="ask question container-fluid" style="margin-top: 2vh;">
            <form method="post"  action="{% url 'CB:AskQuestion'%}">
                 {% csrf_token %}
                <label>
                    <input class="form-control"  placeholder="ask question" name="question">
                    <input type="hidden" name="college" value='{{ college }}'>
                </label>
                <button class="btn btn-success" type="submit">Ask</button>
            </form>
        </div>
    </div>
    <div class="container-fluid" >
        <h4>Reviews</h4>
        <div class="container-fluid" >
        {% for i in review %}
            <p style="margin-top: 1rem; background-color: #F2F2F2; border-radius: 1rem">{{ i.review }}  ~{{ i.user }}</p>
        {% endfor %}
    </div>

        <div class="write review container-fluid" style="margin-top: 2vh;">
            <form method="post" action="{% url 'CB:WriteReview'%}">
                 {% csrf_token %}
                <label>
                    <input class="form-control" placeholder="write review" name="review">
                    <input type="hidden" name="college" value='{{ college }}'>
                </label>
                <button class="btn btn-success" type="submit">Post</button>
            </form>
        </div>
    </div>
    </div>
    </div>

{% endblock %}

templates/homepage.html
{% extends 'base.html' %}

{% block head %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <style>
        .main-container{
            background-color: #094067;
            height: 50vh;
        }
        form{
            padding-top: 20vh;
        }
        .center_div{
            display: flex;
            margin-left: 20vh;
            justify-content: center;
        }
        .btn{
            background-color: #3da9fc;
            color: #fffffe;
            width: 20vh;
        }
        .btn:hover{
            color: #fffffe;
            border: 1px solid aqua;
        }
        .container-sec{
            height: 30vh;
        }
        .content{
            align-content: center;
            width: max-content;
            display: flex;
            margin-top: 30vh;

        }
        .content span{
            font-size: 2rem;
            font-weight: 500;
            color: #094067;
            margin-left: 10rem;
        }
        .autocomplete-items{
            color: aliceblue;
            cursor: pointer;
        }

    </style>
{% endblock %}

{% block body %}
    <div class="container-fluid main-container">
        <div style="height: 40vh">
            <form class="container" autocomplete="off" method="get" action="{% url 'CB:CollegePage' %}">
              <div class="center_div">
                <div class="col-8 autocomplete">
                  <input  id="myInput" name="college" type="text" class="form-control" placeholder="Search College Name">
                </div>
                <div class="col-3">
                    <button type="submit" class="btn mb-2" >Search</button>
                </div>
              </div>
            </form>
        </div>
    </div>
    <div class="container-fluid container-sec">
        <div class="content container-fluid">
            <span>Review Colleges</span>
            <span>Ask Questions</span>
            <span>Connect With People</span>
        </div>
    </div>

    <script>

    function autocomplete(inp, arr) {
      /*the autocomplete function takes two arguments,
      the text field element and an array of possible autocompleted values:*/
      var currentFocus;
      /*execute a function when someone writes in the text field:*/
      inp.addEventListener("input", function(e) {
          var a, b, i, val = this.value;
          /*close any already open lists of autocompleted values*/
          closeAllLists();
          if (!val) { return false;}
          currentFocus = -1;
          /*create a DIV element that will contain the items (values):*/
          a = document.createElement("DIV");
          a.setAttribute("id", this.id + "autocomplete-list");
          a.setAttribute("class", "autocomplete-items");
          /*append the DIV element as a child of the autocomplete container:*/
          this.parentNode.appendChild(a);
          /*for each item in the array...*/
          for (i = 0; i < arr.length; i++) {
            /*check if the item starts with the same letters as the text field value:*/
            if (arr[i].substr(0, val.length).toUpperCase() === val.toUpperCase()) {
              /*create a DIV element for each matching element:*/
              b = document.createElement("DIV");
              /*make the matching letters bold:*/
              b.innerHTML = "<strong>" + arr[i].substr(0, val.length) + "</strong>";
              b.innerHTML += arr[i].substr(val.length);
              /*insert a input field that will hold the current array item's value:*/
              b.innerHTML += "<input type='hidden' value='" + arr[i] + "'>";
              /*execute a function when someone clicks on the item value (DIV element):*/
              b.addEventListener("click", function(e) {
                  /*insert the value for the autocomplete text field:*/
                  inp.value = this.getElementsByTagName("input")[0].value;
                  /*close the list of autocompleted values,
                  (or any other open lists of autocompleted values:*/
                  closeAllLists();
              });
              a.appendChild(b);
            }
          }
      });
      /*execute a function presses a key on the keyboard:*/
      inp.addEventListener("keydown", function(e) {
          var x = document.getElementById(this.id + "autocomplete-list");
          if (x) x = x.getElementsByTagName("div");
          if (e.keyCode === 40) {
            /*If the arrow DOWN key is pressed,
            increase the currentFocus variable:*/
            currentFocus++;
            /*and and make the current item more visible:*/
            addActive(x);
          } else if (e.keyCode === 38) { //up
            /*If the arrow UP key is pressed,
            decrease the currentFocus variable:*/
            currentFocus--;
            /*and and make the current item more visible:*/
            addActive(x);
          } else if (e.keyCode === 13) {
            /*If the ENTER key is pressed, prevent the form from being submitted,*/
            e.preventDefault();
            if (currentFocus > -1) {
              /*and simulate a click on the "active" item:*/
              if (x) x[currentFocus].click();
            }
          }
      });
      function addActive(x) {
        /*a function to classify an item as "active":*/
        if (!x) return false;
        /*start by removing the "active" class on all items:*/
        removeActive(x);
        if (currentFocus >= x.length) currentFocus = 0;
        if (currentFocus < 0) currentFocus = (x.length - 1);
        /*add class "autocomplete-active":*/
        x[currentFocus].classList.add("autocomplete-active");
      }
      function removeActive(x) {
        /*a function to remove the "active" class from all autocomplete items:*/
        for (var i = 0; i < x.length; i++) {
          x[i].classList.remove("autocomplete-active");
        }
      }
      function closeAllLists(elmnt) {
        /*close all autocomplete lists in the document,
        except the one passed as an argument:*/
        var x = document.getElementsByClassName("autocomplete-items");
        for (var i = 0; i < x.length; i++) {
          if (elmnt !== x[i] && elmnt !== inp) {
            x[i].parentNode.removeChild(x[i]);
          }
        }
      }
      /*execute a function when someone clicks in the document:*/
      document.addEventListener("click", function (e) {
          closeAllLists(e.target);
      });
    }
    autocomplete(document.getElementById("myInput"), {{ list|safe }})
    </script>
{% endblock %}

templates/profile.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">


{% block head %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
 <style>
        .head{
            margin-top: 4rem;
        }
        body{
            background-color: #F2F2F2;
        }


    </style>
{% endblock %}

{% block body %}
<div class="container" style="background-color: white;padding-top: 5vh">
    <div class="container-fluid">
        <h1 class="username">{{ username }}</h1>
        <div class="container-fluid, colleges_foll"style="margin-top: 3vh">
            <div class="container"> Colleges Following
                {% for i in collegefollowing %}
                    <p>-{{ i }}</p>
                {% endfor %}

            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="container-fluid, activity">
            <h2 style="margin-top: 5vh">Activity</h2>
            <div>
                <h4>Questions</h4>
                <div class="container-fluid" style="background-color: #F2F2F2; border-radius: 1rem; margin-top: 2rem;">
                <p style="color: #F2F2F2"> yo</p>
                {% for i in question %}
                    <p style="background-color: #fffffe">{{ i.question }}   </p>
                    <p class="text-muted small" style="margin-top: -15px">     ~{{ i.college }}</p>
                {% endfor %}
                <p style="color: #F2F2F2"> yo</p>
                </div>
                <h4>Reviews</h4>
            <div class="container-fluid" style="background-color: #F2F2F2; border-radius: 1rem; margin-top: 2rem;">
                <p style="color: #F2F2F2"> yo</p>
                {% for i in review %}
                     <p style="background-color: #fffffe">{{ i.review }}   </p>
                    <p class="text-muted small" style="margin-top: -15px">     ~{{ i.college }}</p>
                {% endfor %}
             <p style="color: #F2F2F2"> yo</p>
                </div>
            </ul>
        </div>
    </div>
    </div>
<p style="color: white">y</p>
</div>  

{% endblock %}

</html>